{{- $clustername := .Values.cluster.name }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  {{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
  {{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  {{- if .Values.kubernetesVersion }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  {{- end }}
  rkeConfig:
    machinePools:
    {{- if .Values.nodepools }} {{ range $index, $nodepool := .Values.nodepools }}
    - controlPlaneRole: {{ $nodepool.controlplane }}
      etcdRole: {{ $nodepool.etcd }}
      workerRole: {{ $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $nodepool.name }}
      machineConfigRef:
        kind: NutanixConfig
        name: {{ $clustername }}-{{ $nodepool.name }}
      paused: false
      displayName: {{ $nodepool.displayName }}
      {{- if $nodepool.rollingUpdate }}
      rollingUpdate:
        maxUnavailable: {{ $nodepool.rollingUpdate.maxUnavailable }}
        maxSurge: {{ $nodepool.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
    machineGlobalConfig:
      addons_include:
        - https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
      addons: |-
        ---
        apiVersion: v1
        kind: Namespace
        metadata:
          name: metallb-system
        ---
        apiVersion: v1
        kind: ConfigMap
        metadata:
          namespace: metallb-system
          name: metallb-config
        data:
          config: |
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: metal-lb-ip-pool
              namespace: metallb-system
            spec:
              addresses:
              - 10.11.58.120-10.11.58.125
            ---
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: example
              namespace: metallb-system
            spec:
              ipAddressPools:
              - metal-lb-ip-pool
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: rke2-ingress-nginx-controller-loadbalancer
          namespace: kube-system
          labels:
            app.kubernetes.io/component: controller
            app.kubernetes.io/instance: rke2-ingress-nginx
            app.kubernetes.io/name: rke2-ingress-nginx
        spec:
          type: LoadBalancer
          selector:
            app.kubernetes.io/component: controller
            app.kubernetes.io/instance: rke2-ingress-nginx
            app.kubernetes.io/name: rke2-ingress-nginx
          ports:
            - name: http
              port: 80
              targetPort: http
              protocol: TCP
            - name: https
              port: 443
              targetPort: https
              protocol: TCP
      disable:
       - local-storage
       - rke2-snapshot-validation-webhook
       - rke2-snapshot-controller
       - rke2-snapshot-controller-crd
      cni: calico
    {{- if .Values.rke.localClusterAuthEndpoint.enabled }}
    localClusterAuthEndpoint:
      enabled: {{ .Values.rke.localClusterAuthEndpoint.enabled }}
      fqdn: {{ .Values.rke.localClusterAuthEndpoint.fqdn }}
      caCerts: {{ .Values.rke.localClusterAuthEndpoint.caCerts }}
    {{- end }}
    upgradeStrategy:
      controlPlaneDrainOptions:
        enabled: false
        # deleteEmptyDirData: false
        # disableEviction: false
        # gracePeriod: 0
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 0
      workerDrainOptions:
        enabled: false
        # deleteEmptyDirData: false
        # disableEviction: false
        # gracePeriod: 0
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 0
      workerConcurrency: "10%"
      controlPlaneConcurrency: "10%"
{{- if .Values.agentEnvs }}
  agentEnvVars:
{{ toYaml .Values.agentEnvs | indent 4 }}
{{- end }}