{{- if .Values.extraManifests.enabled }}

---
# Install MetalLB CRDs and core components
{{- $metallbContent := .Files.Get "extra-manifests/metal-lb.yaml" }}
{{- if $metallbContent }}
{{ $metallbContent | nindent 0 }}
{{- end }}

---
# Install other resources
{{- range $path, $_ := .Files.Glob "extra-manifests/*.yaml" }}
{{- if ne $path "extra-manifests/metal-lb.yaml" }}
{{- $content := $.Files.Get $path }}
{{- if $content }}
{{ $content | nindent 0 }}
{{- end }}
{{- end }}
{{- end }}