apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: metallb-system
  namespace: fleet-default
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  repo: https://github.com/metallb/metallb
  paths:
  - config/manifests/metallb-crds.yaml
  targetNamespace: metallb-system
  branch: v0.14.8
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: metallb
  namespace: fleet-default
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  repo: https://github.com/metallb/metallb
  paths:
  - config/manifests/metallb-native.yaml
  targetNamespace: metallb-system
  branch: v0.14.8